# Generated by Django 4.1.7 on 2023-03-05 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChatApp', '0002_alter_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='tread_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
